[build]
  publish = "."                   # 前端文件所在目录（根目录）
  functions = "netlify/functions"  # 函数文件所在目录
[functions]
  timeout = 900  # 增加这一行，设置函数超时时间为15分钟（900秒）

[[redirects]]
  from = "/api/*"                 # 匹配所有以/api/开头的请求
  to = "/.netlify/functions/api/:splat"  # 转发到api函数处理
  status = 200                    # 使用200状态码进行代理
  force = true                    # 强制重定向